feat: add support for state sync at specific height
cometbft/cometbft pull request #1922
Opened 2024-01-02 07:55 UTC by Pythonberg1997

### Description

This pr is to introduce an enhancement to support state sync at a specific block height.

### Rationale

In the current code, state sync automatically selects the best (usually the most recent) snapshot for syncing, which may not be very convenient. Sometimes, we might prefer to sync to a specific height of our choosing.

### Changes

Notable changes:
* add support for state sync at a specific block height

---

#### PR checklist

- [ ] Tests written/updated
- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments

2024-01-03 01:23 UTC, melekes requested changes
seems like a reasonable feature-request to me 👍  Thanks for contributing @Pythonberg1997

2024-01-03 01:23 UTC, melekes commented on internal/statesync/snapshots.go
> +		return nil, errors.New("multiple snapshots at height")
from the above comment: "If there are multiple snapshots or no snapshot at the height, it will return nil."

please amend the comment or the code

2024-01-03 01:23 UTC, melekes commented on config/config.go
> +	TargetHeight 	  	int64         `mapstructure:"target_height"`
Please format w/ `make lint-format` or default Go formatter

2024-01-03 01:23 UTC, melekes commented on internal/statesync/snapshots.go
> +	return nil, errors.New("no snapshot at height")
same

2024-01-03 01:23 UTC, melekes commented on config/config.go
> +	TargetHeight 	  	int64         `mapstructure:"target_height"`
Could you add a validation rule in `ValidateBasic` to check that `TargetHeight` is `>= 0`?

2024-01-08 13:50 UTC, cason reviewed
Our policy requires opening an issue before submitting a PR. In that case we can discuss the specifics of the implementation.

Regarding the PR, we would need some test cases to verify the operation of the proposed solution. Moreover, we need documentation and to add the new configuration flag to the configuration file (`config/toml.go`).

2024-01-08 13:50 UTC, cason commented on internal/statesync/syncer.go
> +				if err != nil {
Not finding a snapshot is not a reason for leaving this method. As you can observe after line 174, we try again retrieving the snapshot (we send a further `SnapshotsRequest` to all peers) if, for instance, we didn't receive it yet.

2024-01-08 13:50 UTC, cason commented on internal/statesync/syncer_test.go
We would really need some unit tests covering this new use case.

2024-01-09 10:05 UTC, sergio-mena commented
Following up on @cason 's comment. The way we tackle user requests is to
* first understand the problem we are trying to solve. For that, the user needs to create an issue or a discussion
* once the problem is understood, we then explore the solution space. The user may submit a companion PR containing _one_ possible solution
* a decision is made on why solution/approach will be followed to fix the problem

2024-01-29 12:57 UTC, closed without merging