fix: correctly calculate numFinalBits in getTrueIndices
cometbft/cometbft pull request #2624
Opened 2024-03-16 01:45 UTC by czarcas7ic

I was looking into the bug where seemingly random blocks are only signed by 2/3rd power of validators. The Injective devs said they saw a pattern of larger blocks causing this problem. I then started to look into block parts, and looked into the logic of PickRandom to see if there was potentially a bug in how we "randomly" select blocks. 

While I don't think this is the root cause of the issue (https://github.com/cometbft/cometbft/issues/1742 this is probably more useful in solving the problem we are seeing here), I did come across us handling the last element incorrectly when returning the true indicies. The previous calculation assumes that all previous (numElems-1) are fully accounted for with 64 bits each, but if ba.Bits in not a multiple of 64, then this must be handled differently.

This PR correctly handles the last element in the getTrueIndices method, which is used in PickRandom for propagating block parts.

---

#### PR checklist

- [ ] Tests written/updated
- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments
- [ ] Title follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) spec

2024-03-17 06:00 UTC, melekes approved these changes
Thanks @czarcas7ic ❤️ 

Would be great to cover this with a unit test.

2024-03-17 06:01 UTC, melekes commented
Also, this PR needs a changelog entry.

2024-03-18 12:56 UTC, adizere commented
@czarcas7ic is this needed for backporting to 0.37 for use in Osmosis mainnet? Or is it enough if we backport to 0.38?

2024-03-18 14:53 UTC, czarcas7ic commented
I think it's fine if we can't back port to v0.37. I do think the over arching issue of block parts being propagated when understood should get backported to v0.37

2024-03-18 15:53 UTC, adizere commented
> I think it's fine if we can't back port to v0.37. I do think the over arching issue of block parts being propagated when understood should get backported to v0.37

Cool, thanks!
In general we try to avoid backporting to 0.37 (ref [support policy](https://github.com/cometbft/cometbft/discussions/590)).

2024-03-19 06:03 UTC, melekes requested changes

2024-03-19 06:03 UTC, melekes commented on internal/bits/bit_array.go
> +	numFinalBits := bA.Bits % 64
I'm failing to see how it's different than `numFinalBits := bA.Bits - curBit`.

We'll need a test case.

```go
func TestPickRandomCorrectlyHandlesLastElem(t *testing.T) {
	bA := NewBitArray(128)
	bA.SetIndex(127, true)

	elem, ok := bA.PickRandom()
	require.True(t, ok)
	require.Equal(t, 127, elem)
}
```

2024-03-20 04:38 UTC, closed without merging

2024-03-20 04:38 UTC, czarcas7ic commented
Hm, after writing tests it appears melekes is correct and these are handled the same. My appologies! Closing