perf(consensus): Make late votes outside of last block commits not get to peerMsgQueue
cometbft/cometbft pull request #3157
Opened 2024-05-31 04:19 UTC by ValarDragon

Closes #3154 . Make late votes outside of last blocks precommits not get into the peer msg queue. This lowers the delay for processing more important messages from the peerMsgQueue, and lowers WAL write delays. As noted in the github issue, the number of late votes is actually quite significant.

I don't think theres any test updates needed (all relevant behavior is covered under existing tests. And if you look into the consensus logic, aside from WAL write, all we'd otherwise do is:

```
		cs.Logger.Debug("vote ignored and not added", "vote_height", vote.Height, "cs_height", cs.Height, "peer", peerID)
                return
```

We could still do that if we wanted? But doesn't seem that important, since we have the mark late vote still being sent.

---

#### PR checklist

- [ ] Tests written/updated
- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments
- [ ] Title follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) spec

2024-05-31 05:51 UTC, melekes commented on internal/consensus/reactor.go
> +				isLastBlockPrecommit := msg.Vote.Type != types.PrecommitType || msg.Vote.Height != csHeight-1
```suggestion
				notLastBlockPrecommit := msg.Vote.Type != types.PrecommitType || msg.Vote.Height != csHeight-1
```

2024-05-31 06:11 UTC, ValarDragon commented on internal/consensus/reactor.go
> +				isLastBlockPrecommit := msg.Vote.Type != types.PrecommitType || msg.Vote.Height != csHeight-1
ah ty!

2024-05-31 07:16 UTC, melekes approved these changes
👍

2024-05-31 16:55 UTC, ValarDragon commented
Ah correction this is in v0.37.x, and does cause some very slight overhead.

2024-06-10 13:35 UTC, cason reviewed
We should not spend much resources on messages (any type) which are old  and useless for the consensus protocol. So, the goal here is perfectly legit.

But adding the solution to the consensus _reactor_ is not really the best approach. In fact, the consensus reactor should not take the consensus _state_ lock for every received vote, which is super inefficient in any case. While this PR hasn't introduced this behavior, if we really want to decouple reactor and state, this solution goes towards the wrong direction.

I would instead add this check to the _state_ implementation. The goal is anyway to prevent writing this useless vote to the WAL and keeping the consensus lock for longer than needed.

2024-06-10 20:12 UTC, ValarDragon commented
> But adding the solution to the consensus reactor is not really the best approach. In fact, the consensus reactor should not take the consensus state lock for every received vote, which is super inefficient in any case. While this PR hasn't introduced this behavior, if we really want to decouple reactor and state, this solution goes towards the wrong direction.

My thinking right now is that we can get the lock removed with #3211 , and then have this able to proceed concurrently (not under the single threaded state.go workload)

2024-06-10 20:13 UTC, ValarDragon commented on internal/consensus/reactor.go
> +					cs.metrics.MarkLateVote(msg.Vote.Type)
cs.metrics calls are not, they are all concurrency safe. This is a guarantee provided by go-kit/metrics, which cs.metrics uses

2024-06-10 20:29 UTC, cason commented on .changelog/unreleased/improvements/3157-late-votes-dont-take-cs-mtx.md
> +- [`types`] Significantly speedup types.MakePartSet and types.AddPart, which are used in creating a block proposal
I mean, this is the wrong chngelog entry in my opinion.

2024-06-10 20:52 UTC, ValarDragon commented on .changelog/unreleased/improvements/3157-late-votes-dont-take-cs-mtx.md
> +- [`types`] Significantly speedup types.MakePartSet and types.AddPart, which are used in creating a block proposal
Yes your right, my bad!

2024-07-01 12:48 UTC, cason reviewed
While I don't really like this solution, I do agree it can have good consequences in terms of performance.

My suggestions would render this code as similar as possible as the code in `addVote()` method of `state.go`.

2024-07-01 12:48 UTC, cason commented on .changelog/unreleased/improvements/3157-late-votes-dont-take-cs-mtx.md
> +- [`consensus`] Check for late votes in the reactor, preventing them from entering the
```suggestion
- [`consensus`] Check for late votes in the reactor, preventing them from being delivered to the consensus logic, as a performance optimization.
```

2024-07-01 12:48 UTC, cason commented on .changelog/unreleased/improvements/3157-late-votes-dont-take-cs-mtx.md
> +  ([\#3157](https://github.com/cometbft/cometbft/issues/3157)
I think adding the issue here is the right approach.

2024-07-01 12:48 UTC, cason commented on internal/consensus/reactor.go
> +			// if vote is late, and is not a precommit for the last block, mark it late and return.
```suggestion
			// If a vote is late, and is not a precommit for the last block, mark it late and return.
			// This mimics the logic of `State.addVote()` method.
```

2024-07-01 12:52 UTC, cason requested changes
We need to check a corner case, though.

If a vote is from the current height but from a previous round, we might still need it. We can use it for deciding a block, if its a Precommit, and for accepting a new Proposal, if it is a Prevote for the `PolRound`.

See test units `TestState_PrevotePOLFromPreviousRound` and `TestCommitFromPreviousRound`, for instance.

2024-08-05 05:43 UTC, melekes commented
> We need to check a corner case, though.
> 
> If a vote is from the current height but from a previous round, we might still need it. We can use it for deciding a block, if its a Precommit, and for accepting a new Proposal, if it is a Prevote for the `PolRound`.
> 
> See test units `TestState_PrevotePOLFromPreviousRound` and `TestCommitFromPreviousRound`, for instance.

@cason could you check this? Then, if we need these votes, we can close this PR. If not, merge this PR.

2024-08-05 12:08 UTC, cason commented
> @cason could you check this? Then, if we need these votes, we can close this PR. If not, merge this PR.

We would have to make a copy of those tests that run with a reactor, instead of manually providing messages to the consensus implementation. This is not so trivial, unfortunately.

But in general I am pretty convinced that we need in some cases messages from previous rounds, these tests are just some examples.

2024-08-20 11:35 UTC, cason commented
We cannot discard votes from previous rounds because the algorithm may require those votes to progress.

The problem here is that our test units test consensus `State` where we deliver the messages we want it to process. Adapting these tests to rely on a reactor, i.e., messages received from peers is not simple.

If you manage to adapt the two mentioned tests to run with a consensus `Reactor` and they do not fail I will be surprised but accept this change.

2024-09-09 08:07 UTC, closed without merging