Make reactor check for duplicate/old block parts
cometbft/cometbft pull request #3161
Opened 2024-05-31 14:21 UTC by ValarDragon

Closes #3158 

I made a common method between the reactor and consensus. In the future may add another argument to indicate if it should check the block part, but decided to not try that until I got vote signature checking into the reactor, as thats the bottleneck for Osmosis right now. (I suspect WAL is dominated from here though, will be straightforward to check once this is merged / in a patch release that I can A/B test)

---

#### PR checklist

- [ ] Tests written/updated
- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments
- [ ] Title follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) spec

2024-06-03 07:54 UTC, melekes approved these changes
Thanks @ValarDragon ❤️

2024-06-03 07:54 UTC, melekes commented on internal/consensus/state.go
> +	// TODO: better handle block parts for future heights, by saving them and processing them later.
do you mind opening an issue for this?

2024-06-26 05:18 UTC, melekes approved these changes

2024-07-01 13:02 UTC, cason requested changes
We could change our mind regarding the Block we are looking for at any given instant.

We usually initialize `cs.ProposalBlockParts` upon receiving the first valid `Proposal` message for that round. But we might reset it upon receiving 2/3+ Prevotes or Precommits for a different block.

As a result, we might drop a block part that matches the new Block we are looking for, because we didn't change the block we are looking for because we are still processing votes that might made us to change our mind.

2024-07-11 06:21 UTC, melekes commented
@cason are you saying that because we can change our minds about `cs.ProposalBlockParts` at any moment, we should still write "invalid" block parts to WAL because between the time we write them and try to add them to `cs.ProposalBlockParts`, `cs.ProposalBlockParts` might have changed?

I'm in favor of this PR because, in most cases, we don't change our minds, and preventing duplicate parts from entering WAL as a perf optimization makes sense to me.

2024-07-12 08:14 UTC, cason commented
> @cason are you saying that because we can change our minds about `cs.ProposalBlockParts` at any moment, we should still write "invalid" block parts to WAL because between the time we write them and try to add them to `cs.ProposalBlockParts`, `cs.ProposalBlockParts` might have changed and "invalid" block part may "become valid"?
> 
> I'm in favor of this PR because, in most cases, we don't change our minds, and preventing duplicate parts from entering WAL as a perf optimization makes sense to me.

So, first, I don't think we should write block parts to the WAL at all. Except if we are using the full block. Namely, we either write the full block, or nothing. The best way to achieve this is to move block propagation outside of the consensus logic, which is the right direction to go.

At the moment, what can happen, and we might even write a test unit for that is:

- I am looking for block `X`, because we received a `Proposal` for `id(X)`
- But I am receiving votes (either type) for `id(Y) != id(X)`
- When I get 2/3+ of such votes, I will drop the block parts and part set of `X` and replace the block part set structure to accept block `Y`
- Meanwhile, I start receiving parts of block `Y`

So, if I receive a part of block `Y` at the reactor level but the votes that will make me change my mind are still on the queue to be processed, we are rejecting, basing on our current state, something we should accept, that we need by the way. Of course, if we don't mark that part as received, we should eventually get it again. But this is something to be tested, in my opinion.

2024-07-12 08:49 UTC, melekes commented
> Of course, if we don't mark that part as received, we should eventually get it again. But this is something to be tested, in my opinion.

@ValarDragon did you roll this out in production? Are you observing any slowness or blocks failing to commit as a consequence of this PR?

2024-07-12 09:11 UTC, cason commented
This should be done as part of this https://github.com/cometbft/cometbft/issues/2127

2024-08-05 05:45 UTC, melekes commented
> > Of course, if we don't mark that part as received, we should eventually get it again. But this is something to be tested, in my opinion.
> 
> @ValarDragon did you roll this out in production? Are you observing any slowness or blocks failing to commit as a consequence of this PR?

cc @ValarDragon

2024-08-19 19:58 UTC, ValarDragon commented
This has been in prod on Osmosis for ~2 months, no issues observed :)

2024-08-20 11:30 UTC, cason commented
We are probably not seen issues derived from this optimization in stable systems. This happens in a real corner case when we change the block we are looking at after receiving prevotes for that block, that does not match the proposed block. Which essentially requires Byzantine agents.

2024-09-04 00:15 UTC, closed without merging