chore(ticker): Prevent ticker from blocking
cometbft/cometbft pull request #3317
Opened 2024-06-23 01:12 UTC by itsdevbear

---

#### PR checklist

- [ ] Tests written/updated
- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments
- [ ] Title follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) spec

2024-06-24 06:26 UTC, melekes reviewed
Thanks @itsdevbear ❤️

2024-06-24 06:26 UTC, melekes commented on internal/consensus/ticker.go
> +	select {
What triggered this change? Did you encounter a case where Comet blocks here for a prolonged period?

2024-06-24 06:26 UTC, melekes commented on internal/consensus/ticker.go
> +			select {
same question

2024-06-26 02:52 UTC, ValarDragon commented
I'm confused whats the cause of this. inputs to TickChan should be single threaded, so we won't get blocking behavior adding to the queue.

If theres a problem here, imo we just raise the Tick channel buffer to like 100. That should basically cost us nothing, and lower any probability of blocking behavior anyway

2024-06-26 14:21 UTC, cason commented
I agree that just increasing the size of the buffer should be enough. But the question is: how many threads are scheduling timeouts at a time? I thing there is a single one.

2024-07-05 07:45 UTC, cason requested changes
I will block this PR because:

- We probably cannot afford _not_ scheduling a timeout for some internal channel problems in the ticker
- We don't have any evidence that this situation may actually occur and affect performance

2024-07-10 06:13 UTC, melekes commented
Given the above comments and no response from the PR's author, I am closing this. @itsdevbear, if/when you find some time to respond to the comments, please do so, and we'll happily reconsider the changes.

2024-07-10 06:13 UTC, closed without merging