feat(config): Log possible misconfiguration
cometbft/cometbft pull request #3641
Opened 2024-08-06 23:09 UTC by najeal

This PR has originally been opened on Celestia fork of cometbft to resolve this issue : https://github.com/celestiaorg/celestia-app/issues/3736

This adds warn logs when state sync RPCServers are set while enable = false as it may lead to unexpected behavior whereas Config is valid.

#### PR checklist

- [X] Tests written/updated
- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments
- [ ] Title follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) spec

2024-08-07 05:21 UTC, melekes approved these changes
Love this solution ❤️ 

I'm not sure we need a new log level, but I'm okay with adding it.

2024-08-07 10:13 UTC, najeal commented
The possible misconfiguration can be logged as an Info and I delete the changes in the log package if you prefer 👍

2024-08-08 20:59 UTC, najeal commented
Warn log has been deleted

2024-08-09 05:00 UTC, melekes approved these changes

2024-08-09 08:59 UTC, melekes requested changes

2024-08-09 08:59 UTC, melekes commented on config/config.go
> +		res = append(res, "[statesync] section: %s"+elem)
```suggestion
		res = append(res, "[statesync] section: "+elem)
```

2024-08-09 09:00 UTC, melekes approved these changes

2024-08-09 09:27 UTC, merged