feat(e2e): `config` flag for arbitrary CometBFT configurations
cometbft/cometbft pull request #3967
Opened 2024-09-02 13:45 UTC by cason

Closes #3832.

Introduces a flag `config` to the manifest. It is a list of strings that should have the format `key = value`. Keys are any of the configuration parameters included in a CometBFT configuration file.

The flag can be global, meaning that the configurations will be applied for every node in the network, or specific for a given node, when inserted in the section referring to that node. Local/specific configurations are applied after the global ones, therefore overriding them.

Example:

```
config = [
   "p2p.send_rate = 51200",
   "filter_peers = true",
]
```

The configurations are applying using `viper`, as I could not find another way to load configuration parameters. They are always loaded as a string, and this appears to work correctly.

Note: this PR is based atop #3964 for simplicity, but it does not need to.

---

#### PR checklist

- [ ] Tests written/updated
- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments

2024-09-02 14:34 UTC, melekes approved these changes
👍

2024-09-02 14:34 UTC, melekes commented on test/e2e/pkg/manifest.go
> +	// Example: "p2p.send_rate = 512000.
```suggestion
	// Example: "p2p.send_rate = 512000".
```

2024-09-02 14:34 UTC, melekes commented on test/e2e/pkg/manifest.go
> +	// Example: "p2p.send_rate = 512000.
```suggestion
	// Example: "p2p.send_rate = 512000".
```

2024-09-03 10:39 UTC, hvanz commented
Wouldn't it be better to use in the manifest the `Config` struct of the `config` package instead of strings of the form`"key = value"`? Then in the manifest one could write
```
[node.validator01]
config.P2P.send_rate = 512000
```
That way we don't need to care when the configuration changes, and we can reuse the existing validation functions.

2024-09-03 11:09 UTC, cason commented
> Wouldn't it be better to use in the manifest the `Config` struct of the `config` package instead of strings of the form`"key = value"`? Then in the manifest one could write
> 
> ```
> [node.validator01]
> config.P2P.send_rate = 512000
> ```
> 
> That way we don't need to care when the configuration changes, and we can reuse the existing validation functions.

That was my original idea, but it does not work.

The `Config` object use the Viper setup, which `mapstructure` tags. Which are not recognized by the `toml` package we use to decode the manifest.

2024-09-03 11:10 UTC, cason commented
> That way we don't need to care when the configuration changes, and we can reuse the existing validation functions.

We still check the config parameters, as we call the validate method.

2024-09-03 11:19 UTC, hvanz commented
> The Config object use the Viper setup, with mapstructure tags. Which are not recognized by the toml package we use to decode the manifest.

yeah, I thought about that. We would need to use the `mapstructure` tags in the manifest too instead of the `toml` tags. But I guess the implementation would be quite different from this PR.

2024-09-03 11:22 UTC, cason commented
> yeah, I thought about that. We would need to use the mapstructure tags in the manifest too instead of the toml tags. 

Initially I was thinking on the opposite direction, namely, getting riding of this dependency on Viper. But after playing a little with it, we probably should use viper on e2e as well.

Notice that we don't need necessarily to use the `mapstructure` tag, see the companion PR for the genesis file. We can change the tag Viper uses, but we need to be consistent.

2024-09-03 14:31 UTC, andynog requested changes
I think this logic is not working properly. Seems that the way is implemented might produce unnecessary behaviors. 

Quick test.

Had a simple manifest
```
config = [
    "p2p.send_rate = 51200",
    "filter_peers = true",
]

[node.validator]
```

This emitted 
```
(e2e) > ./build/runner -f networks/single.toml setup
I[2024-09-03|14:25:08.905] setup                                        msg="Generating testnet files in `networks/single`"
D[2024-09-03|14:25:08.906] Applying Comet config                        node=validator p2p.send_rate=51200
D[2024-09-03|14:25:08.906] Applying Comet config                        node=validator filter_peers=true
```

Checked the config and value for `filter_peers` was set
```
# If true, query the ABCI app on connecting to a new peer
# so the app can decide if we should keep the connection or not
filter_peers = true
```

But let's say I've misspelled the field name as `filter_peer` (singular not plural)
```
config = [
    "p2p.send_rate = 51200",
    "filter_peer = true",
]

[node.validator]
```

Then when I ran the runner `./build/runner -f networks/single.toml setup`, the runner accepted that field as if it was valid
```
(e2e) > ./build/runner -f networks/single.toml setup
I[2024-09-03|14:24:12.991] setup                                        msg="Generating testnet files in `networks/single`"
D[2024-09-03|14:24:12.992] Applying Comet config                        node=validator p2p.send_rate=51200
D[2024-09-03|14:24:12.992] Applying Comet config                        node=validator filter_peer=true
```
But in the generated `config.toml` the `filter_peers` is `false`
```
filter_peers = false
```
So if we are accepting these configuration as a "key = value" specified as a string, I think we need to at least validate that the `key` matches a real field in the `config` to avoid problems with renames or false expectations when running tests.

2024-09-03 18:13 UTC, cason commented
> So if we are accepting these configuration as a "key = value" specified as a string, I think we need to at least validate that the key matches a real field in the config to avoid problems with renames or false expectations when running tests.

I agree, but how to do that?

2024-09-03 21:00 UTC, andynog approved these changes
I will just unblock this, my previous comment is still valid but the implementation to solve the validation problem is not easy. Might need a future PR if we can get it to work.

2024-09-04 13:30 UTC, merged