e2e: allow customizing genesis parameters on the manifest
cometbft/cometbft pull request #3969
Opened 2024-09-02 15:54 UTC by cason

---

#### PR checklist

- [ ] Tests written/updated
- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments

2024-09-03 04:16 UTC, melekes approved these changes
👍

2024-09-03 08:39 UTC, cason commented
There is a lint error I don't have idea what it means:
```
 golangci-lint-full.......................................................Failed
- hook id: golangci-lint-full
- exit code: 1

WARN The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar. 
test/e2e/runner/setup.go:18:2: import 'github.com/mitchellh/mapstructure' is not allowed from list 'main' (depguard)
	"github.com/mitchellh/mapstructure"
	^
```

2024-09-03 14:37 UTC, andynog requested changes
Same comment made in #3967 

We need to validate the `key` with a valid field in `genesis` otherwise we might get undesired behaviors


```
(e2e) > ./build/runner -f networks/single.toml setup
I[2024-09-03|14:34:21.615] setup                                        msg="Generating testnet files in `networks/single`"
D[2024-09-03|14:34:21.616] Applying Genesis config                      consensus_params.evidence.max_bytes=1000
D[2024-09-03|14:34:21.616] Applying Genesis config                      chain_id=pr3969
```

here `chain_id` was set in the `genesis.json` file, but mispelling the field name to `chainid` 

```
(e2e) > ./build/runner -f networks/single.toml setup
I[2024-09-03|14:34:32.827] setup                                        msg="Generating testnet files in `networks/single`"
D[2024-09-03|14:34:32.827] Applying Genesis config                      consensus_params.evidence.max_bytes=1000
D[2024-09-03|14:34:32.827] Applying Genesis config                      chainid=pr3969
```

validation accepted invalid field name, so of course it was not set
```
{
  "genesis_time": "2024-09-03T14:34:32.827736Z",
  "chain_id": "single",
```

2024-09-03 21:00 UTC, andynog approved these changes
I will just unblock this, my previous comment is still valid but the implementation to solve the validation problem is not easy. Might need a future PR if we can get it to work.

2024-09-04 13:50 UTC, cason commented on test/e2e/pkg/testnet.go
> +
```suggestion
```

2024-09-04 14:03 UTC, merged