fix(mempool): Pass cancellable context to iterator
cometbft/cometbft pull request #4058
Opened 2024-09-10 10:53 UTC by hvanz

Fixes #4057

---

#### PR checklist

- [ ] Tests written/updated
- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments

2024-09-10 11:09 UTC, jmalicevic approved these changes

2024-09-11 08:18 UTC, melekes requested changes

2024-09-11 08:18 UTC, melekes commented on mempool/reactor.go
> +		case <-ctx.Done():
This is never reached.

2024-09-11 08:18 UTC, melekes commented on mempool/clist_mempool.go
> +			case <-iter.ctx.Done():
Do you think we shouldn't exit here?

```suggestion
			case <-iter.ctx.Done():
			   close(ch)
			   return
```

2024-09-11 08:18 UTC, melekes commented on mempool/clist_mempool.go
> +			case <-iter.ctx.Done():
Do you think we shouldn't exit here?

```suggestion
			case <-iter.ctx.Done():
			   close(ch)
			   return
```

2024-09-11 11:11 UTC, hvanz commented on mempool/reactor.go
> +		case <-ctx.Done():
That's correct. I removed it.

2024-09-11 11:16 UTC, melekes approved these changes

2024-09-11 13:21 UTC, merged