p2p: adjust backoff seconds to increase retry up to 1 day
cometbft/cometbft pull request #4377
Opened 2024-10-31 18:26 UTC by andynog

close: #3519 

Adjust `reconnectBackOffBaseSeconds` to increase reconnect retries to up 1 day (~24 hours).

The new value can be validated here: https://go.dev/play/p/k8F5rS-i24p, which will show that the total time is increased to almost 24 hours. 

Initial reconnecting time: 2m8.493s
Total reconnecting time. : 23h55m56.249s

The `reconnectBackOffBaseSeconds` is increased by a bit over 10% (from 3.0 to 3.4 seconds) so this would not affect reconnection retries too much.

#### PR checklist

- [ ] Tests written/updated
- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments

2024-11-01 05:14 UTC, melekes approved these changes
👍

2024-11-04 08:33 UTC, cason commented
Hum, I think the problem is not on the base of the backoff, but the fact that the second loop starts from `0`:

https://go.dev/play/p/mm3Hb13m5Cs

2024-11-04 08:36 UTC, cason requested changes
Thank you for addressing this, but I think the solution goes in another direction (see my comments).

2024-11-04 08:36 UTC, cason commented on p2p/switch.go
> +// exponential backoff (approximately close to 24 hours).
The problem here for me is the second four (lines 424/426) starts from 0. Anything with power 0 == 1.

2024-11-04 16:24 UTC, andynog commented
Thanks @cason, I've made the suggested changes.

2024-11-04 16:30 UTC, cason approved these changes
Thank for this. There is a `<` that must become `<=`.

2024-11-04 16:30 UTC, cason commented on p2p/switch.go
> +	for i := 1; i < reconnectBackOffAttempts; i++ {
```suggestion
	for i := 1; i <= reconnectBackOffAttempts; i++ {
```

2024-11-04 16:30 UTC, cason commented on p2p/switch.go
> +	for i := 1; i < reconnectBackOffAttempts; i++ {
Otherwise it takes 8h.

2024-11-04 16:44 UTC, andynog commented
Thanks @cason, should we also back port this to `v0.38.x` and `v0.37.x` seems the logic is the same.

2024-11-04 16:47 UTC, cason commented
> should we also back port this to v0.38.x and v0.37.x seems the logic is the same.

I think we should.

2024-11-04 19:57 UTC, merged