p2p: kcp instead of tcp
cometbft/cometbft pull request #639
Opened 2023-04-03 17:34 UTC by faddat

I am nearly certain that this isn't a priority, and that's no big deal.  

From time to time I would remember this PR, which I wrote while playing about with Sei and getting 40% uptime from Vietnam. 

Theoretically speaking (and indeed I do think in practice) this replaces the tcp transport that comet uses with kcp, which....

https://github.com/skywind3000/kcp

https://ims.improbable.io/insights/kcp-a-new-low-latency-secure-network-stack

https://mirror-networking.gitbook.io/docs/manual/transports/kcp-transport

------

Theoretically, this would make comet faster, but we'd need a (crazy) testnet to know. 
---

#### PR checklist

- [ ] Tests written/updated
- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments

2023-04-03 19:32 UTC, peterbourgon requested changes
CometBFT's P2P layer is not defined by this particular implementation, it is defined by [a specification](https://github.com/cometbft/cometbft/blob/main/spec/p2p/node.md) which explicitly specifies [P2P connections as TCP](https://github.com/cometbft/cometbft/blob/main/spec/p2p/connection.md). 

More generally, changes in fundamental subsystems like the p2p layer need to be motivated by well-defined requirements that are agreed upon by all stakeholders, and they need to substantiated by concrete evidence that the proposed changes satisfy those requirements. This PR provides neither agreed-upon requirements, nor evidence that proposed change satisfies those requirements.

2023-04-03 19:32 UTC, peterbourgon commented on p2p/netaddress.go
> +			panic(fmt.Sprintf("Only UDPAddrs are supported. Got: %v", addr))
If you want to add support for a novel transport-level protocol like KCP (which also switches the network-layer protocol from TCP to UDP) you can't just redefine a core function like NewNetAddress to use your alternative by default, you have to make it opt-in.

2023-04-03 19:32 UTC, peterbourgon commented on p2p/transport.go
>  	}
You're totally ignoring addr.

2023-04-04 15:35 UTC, faddat commented
Oh yes totally that is all accurate sir. I put this out mainly as a proof
of concept and well dealing with ADDR sounds like a really good idea, and
when I first made this PR the idea was actually to support TCP,  quic, and
KCP.

But that was back in the days before comet you see.

Also it wasn't quite done I was just really surprised that anything worked
with it to be quite honest with you sir.

Is this an interesting direction? Or is it a potshot?

Thank you for your review


On Tue, Apr 4, 2023, 2:32 AM Peter Bourgon ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> CometBFT's P2P layer is not defined by this particular implementation, it
> is defined by a specification
> <https://github.com/cometbft/cometbft/blob/main/spec/p2p/node.md> which
> explicitly specifies P2P connections as TCP
> <https://github.com/cometbft/cometbft/blob/main/spec/p2p/connection.md>.
>
> More generally, changes in fundamental subsystems like the p2p layer can't
> just be made based on presumptive claims. They need to be motivated by
> well-defined requirements that are agreed upon by all stakeholders, and
> they need to substantiated by concrete evidence that the proposed changes
> satisfy those requirements. This PR provides neither requirements nor
> evidence.
> ------------------------------
>
> In p2p/netaddress.go
> <https://github.com/cometbft/cometbft/pull/639#discussion_r1156362784>:
>
> > -	tcpAddr, ok := addr.(*net.TCPAddr)
> +	tcpAddr, ok := addr.(*net.UDPAddr)
>  	if !ok {
>  		if flag.Lookup("test.v") == nil { // normal run
> -			panic(fmt.Sprintf("Only TCPAddrs are supported. Got: %v", addr))
> +			panic(fmt.Sprintf("Only UDPAddrs are supported. Got: %v", addr))
>
> If you want to add support for a novel transport-level protocol like KCP
> (which also switches the network-layer protocol from TCP to UDP) you can't
> just redefine a core function like NewNetAddress to use your alternative by
> default, you have to make it opt-in.
> ------------------------------
>
> In p2p/transport.go
> <https://github.com/cometbft/cometbft/pull/639#discussion_r1156366043>:
>
> > -	ln, err := net.Listen("tcp", addr.DialString())
> +
> +	ln, err := kcp.Listen("0.0.0.0:26656")
>  	if err != nil {
>  		return err
>  	}
>
> You're totally ignoring addr.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/cometbft/cometbft/pull/639#pullrequestreview-1369651851>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABWPVCL7BTX55VN5JPMR4NDW7MQWTANCNFSM6AAAAAAWRUB2FA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-04-19 00:13 UTC, closed without merging